name: Links Checker (Lychee)

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'assignments/**'
      - 'tickframe/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'assignments/**'
      - 'tickframe/**'

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Link Checker
        uses: lycheeverse/lychee-action@v2
        with:
          args: --verbose --no-progress --exclude 'https?://.*' --exclude 'http://' --exclude 'https?://(?:localhost|127\.0\.0\.1):(?:8080|8001)(?:[/?#].*)?' --exclude 'https://gitlab\.pg\.innopolis\.university' --exclude 'https://drive\.google\.com' --exclude 'releases/tag/v0\.2\.0' --exclude 'releases/tag/SemVer-MVPv1' --exclude 'file://' --exclude-path 'assignments/' './**/*.md'
          fail: true